import { globalColors } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const adminStyles = StyleSheet.create({
  container: { backgroundColor: globalColors.primary },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  errorMsg: { color: "#b00", textAlign: "center", margin: 8 },
  scrollContent: { paddingHorizontal: 10, paddingBottom: 10 },

  usersList: { marginBottom: 24, marginTop: 12 },
  userContainer: {
    position: "relative",
    maxWidth: 150,
    backgroundColor: "#f4f4f4",
    paddingHorizontal: 12,
    paddingVertical: 20,
    borderRadius: 8,
    marginBottom: 12,
    marginHorizontal: 8,
    // Shadow for iOS
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    // Elevation for Android
    elevation: 3,
  },
  userBanned: {
    backgroundColor: "#ffe6e6",
    borderWidth: 1,
    borderColor: "#b002e2",
  },
  userAdmin: {
    backgroundColor: "#e6ffe6",
    borderWidth: 1,
    borderColor: "#123000",
    shadowColor: "#123000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  deleteIcon: {
    position: "absolute",
    top: -16,
    right: -12,
    zIndex: 1,
    backgroundColor: "#f4f4f4",
    borderRadius: 30,
    padding: 2,
  },
  formContainer: {
    backgroundColor: "transparent",
    borderRadius: 10,
    padding: 16,
    elevation: 1,
  },
  inputGroup: { position: "relative", marginBottom: 12 },
  label: { marginBottom: 4, fontWeight: "bold" },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    padding: 8,
    backgroundColor: "#fff",
  },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 4,
  },
  section: { marginTop: 12, marginBottom: 6 },
  sectionTitle: { fontWeight: "bold", color: "#007AFF", marginBottom: 4 },
  buttonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 8,
  },
  button: {
    flex: 1,
    backgroundColor: "#eee",
    padding: 10,
    borderRadius: 6,
    marginHorizontal: 4,
    alignItems: "center",
  },
  showPasswordButton: {
    position: "absolute",
    top: 20,
    right: 14,
    alignItems: "center",
    backgroundColor: "transparent",
  },
  saveButton: {
    flex: 1,
    backgroundColor: "#007AFF",
    padding: 12,
    borderRadius: 6,
    marginHorizontal: 4,
    alignItems: "center",
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#bbb",
    padding: 12,
    borderRadius: 6,
    marginHorizontal: 4,
    alignItems: "center",
  },
  cancelButtonText: { color: "#fff", fontWeight: "bold" },
});
