export const getFriendlyUnitName = (name: string): string => {
  const unitNameMapping: { [key: string]: string } = {
    FloorHockey: "Floor Hockey",
    FinnishBaseball: "Finnish Baseball",
    TrackAndField: "Track & Field",
    StrikeAndField: "Strike & Field",
    InvasionGames: "Invasion Games",
    RollerSkating: "Roller Skating",
    CircuitTraining: "Circuit Training",
    OutdoorAdventureActivity: "Outdoor Adventure Activities",
    WaterSkills: "Water Skills",
    BatAndBall: "Bat & Ball",
    CompetitiveGames: "Competitive Games",
    BallGames: "Ball Games",
    ObjectControlSkills: "Object Control Skills",
    LocomotorSkills: "Locomotor Skills",
    MusicRhythmsAndMovementActivities: "Music, Rhythms & Movement",
    PhysicalExercises: "Physical Exercises",
    MovingAndGrooving: "Moving & Grooving",
    RhythmAndPlay: "Rhythm & Play",
    SensoryAdventures: "Sensory Adventures",
    TeamworkInAction: "Teamwork In Action",
    MightyMovers: "Mighty Movers",
    HandsOnFun: "Hands On Fun",
    BalancingAct: "Balancing Act",
    TargetGames: "Target Games",
    BasicTrackAndField: "Basic Track & Field",
    AttackingAndDefending: "Attacking & Defending",
    DancePlants: "Dance Plants",
    FitnessFun: "Fitness Fun: Know My Body",
    NetWallFundamentals: "Net/Wall: Fundamentals",
    OutdoorActivities: "Outdoor Adventure Activities",
    FlagFootBall: "NFL Flag Football",
    CooperativeGames: "Cooperative Games",
    TerritoryGames: "Territory Games",
    HealthAndFitness: "Health & Fitness",
  };

  return unitNameMapping[name] || name;
};
