import { StoredUsers } from "../user/IUser";

export const initialUserState: StoredUsers = {
  name: "",
  email: "",
  password: "",
  role: "user",
  baned: false,
  pk3: {
    BalancingAct: false,
    HandsOnFun: false,
    MightyMovers: false,
    MovingAndGrooving: false,
    RhythmAndPlay: false,
    SensoryAdventures: false,
    TeamworkInAction: false,
  },
  pk4: {
    BalancingAct: false,
    Gymnastics: false,
    HandsOnFun: false,
    MightyMovers: false,
    MovingAndGrooving: false,
    RhythmAndPlay: false,
    SensoryAdventures: false,
    TeamworkInAction: false,
  },
  kg: {
    BallGames: false,
    BatAndBall: false,
    CompetitiveGames: false,
    LocomotorSkills: false,
    MusicRhythmsAndMovementActivities: false,
    ObjectControlSkills: false,
    PhysicalExercises: false,
    WaterSkills: false,
  },
  first: {
    InvasionGames: false,
    TargetGames: false,
    Gymnastics: false,
    BasicTrackAndField: false,
    FitnessFun: false,
    AttackingAndDefending: false,
    Swimming: false,
    DancePlants: false,
    BatAndBall: false,
  },
  second: {
    InvasionGames: false,
    OutdoorActivities: false,
    DodgeBall: false,
    Gymnastics: false,
    Athletics: false,
    CircuitTraining: false,
    Swimming: false,
    NetWallFundamentals: false,
    Basketball: false,
  },
  third: {
    Athletics: false,
    CircuitTraining: false,
    Gymnastics: false,
    InvasionGames: false,
    Badminton: false,
    StrikeAndField: false,
  },
  fourth: {
    Badminton: false,
    Basketball: false,
    CircuitTraining: false,
    FinnishBaseball: false,
    Football: false,
    Gymnastics: false,
    InvasionGames: false,
    RollerSkating: false,
    Swimming: false,
    TrackAndField: false,
  },
  fifth: {
    Dodgeball: false,
    FinnishBaseball: false,
    Soccer: false,
    Swimming: false,
    FloorHockey: false,
  },
};
