export const gradeKeys = [
  "pk3",
  "pk4",
  "kg",
  "first",
  "second",
  "third",
  "fourth",
  "fifth",
  "sixth",
  "seventh",
  "eighth",
  "ninth",
  "tenth",
  "eleventh",
  "twelfth",
] as const;

export const titleMap: Record<string, string> = {
  pk3: "PK3",
  pk4: "PK4",
  kg: "Kindergarten",
  first: "1st Grade",
  second: "2nd Grade",
  third: "3rd Grade",
  fourth: "4th Grade",
  fifth: "5th Grade",
  sixth: "6th Grade",
  seventh: "7th Grade",
  eighth: "8th Grade",
  ninth: "9th Grade",
  tenth: "10th Grade",
  eleventh: "11th Grade",
  twelfth: "12th Grade",
};
