import { StyleSheet } from "react-native";

export const authStyles = StyleSheet.create({
  screen: {
    flex: 1,
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "stretch",
    paddingHorizontal: 0,
    backgroundColor: "#020617",
  },
  card: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.98)",
    borderRadius: 0,
    padding: 24,
    paddingTop: 60,
    paddingBottom: 60,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.4,
    shadowRadius: 28,
    elevation: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#f9fafb",
    marginBottom: 8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    color: "#9ca3af",
    marginBottom: 24,
    textAlign: "center",
  },
  errorText: {
    color: "#f97373",
    backgroundColor: "rgba(249,115,115,0.1)",
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    textAlign: "center",
  },
  infoText: {
    color: "#4ade80",
    backgroundColor: "rgba(74,222,128,0.1)",
    padding: 12,
    borderRadius: 10,
    marginBottom: 16,
    textAlign: "center",
  },
  inputGroup: {
    marginBottom: 2,
  },
  inputGroupRow: {
    maxWidth: "56%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: 144,
    marginTop: 2,
  },
  inputGroupRowButtons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    borderColor: "#4b5563",
    paddingHorizontal: 36,
    paddingVertical: 7,
    borderWidth: 2,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#e5e7eb",
    marginBottom: 6,
  },
  input: {
    width: "96%",
    height: 48,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#4b5563",
    paddingHorizontal: 16,
    backgroundColor: "rgba(15,23,42,0.9)",
    color: "#f9fafb",
    fontSize: 16,
  },
  passwordContainer: {
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
  },
  inputPassword: {
    paddingRight: 60,
  },
  eyeIcon: {
    position: "absolute",
    right: 30,
    padding: 8,
  },
  eyeIconText: {
    fontSize: 22,
  },
  generateBtn: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginRight: 16,
    backgroundColor: "rgba(34, 197, 94, 0.15)",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(34, 197, 94, 0.4)",
    alignSelf: "flex-end",
  },
  generateBtnText: {
    color: "#22c55e",
    fontSize: 14,
    fontWeight: "600",
  },
  btn: {
    marginTop: 20,
    borderRadius: 999,
    alignItems: "center",
    backgroundColor: "#2563eb",
    paddingVertical: 16,
  },
  btnDisabled: {
    opacity: 0.7,
  },
  linkRight: {
    marginTop: 12,
    alignSelf: "flex-end",
  },
  linkTextSmall: {
    fontSize: 13,
    color: "#60a5fa",
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 24,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(55,65,81,0.8)",
  },
  dividerText: {
    marginHorizontal: 12,
    color: "#6b7280",
    fontSize: 14,
    fontWeight: "500",
  },
  switchRow: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  switchText: {
    color: "#9ca3af",
    fontSize: 15,
  },
  switchLink: {
    marginLeft: 8,
    fontSize: 15,
    fontWeight: "700",
    color: "#60a5fa",
  },
});
