import { Dimensions, StyleSheet } from "react-native";

const windowWidth = Dimensions.get("window").width;

export const profileStyles = StyleSheet.create({
  container: {
    paddingBottom: 90,
  },
  header: {
    fontSize: 24,
    fontWeight: "700",
    marginLeft: 16,
    marginBottom: 16,
    color: "#0F172A",
  },
  buttonContainer: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 16,
    marginVertical: 12,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  gradeContainer: {
    marginBottom: 20,
  },
  gradeHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    justifyContent: "space-between",
    paddingRight: 26,
  },
  gradeTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginLeft: 16,
    marginBottom: 12,
    color: "#333",
  },
  activeSportsText: {
    marginLeft: 12,
    fontSize: 16,
    fontWeight: "500",
    color: "#444",
    fontFamily: "Roboto",
    textOverflow: "ellipsis",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1,
    elevation: 2,
    lineHeight: 20,
    backgroundColor: "#ffffff",
    padding: 6,
    borderRadius: 6,
    minWidth: 160,
    textAlign: "center",
  },
  sportItem: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 9,
    justifyContent: "center",
    alignItems: "center",
    minWidth: windowWidth * 0.28,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  activeSport: {
    backgroundColor: "#002f02b5",
    borderColor: "#004d00b5",
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 5,
  },
  inactiveSport: {
    backgroundColor: "#ddd",
    borderColor: "#ccc",
  },
  sportText: {
    fontSize: 14,
  },
  activeText: {
    color: "#fff",
    fontWeight: "800",
  },
  inactiveText: {
    color: "#666",
    fontWeight: "600",
  },
  emptyContainer: {
    marginTop: 40,
    alignItems: "center",
  },
});

export const userProfileStyles = StyleSheet.create({
  container: {
    backgroundColor: "#F8FAFC",
    width: "100%",
    borderRadius: 16,
    padding: 0,
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 100,
    paddingTop: 8,
    backgroundColor: "#F8FAFC",
    alignItems: "center",
  },
  profileCard: {
    width: "100%",
    position: "relative",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  renderMsg: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderWidth: 1,
    padding: 8,
    borderRadius: 10,
    marginBottom: 8,
    marginHorizontal: 4,
    marginTop: 12,
    backgroundColor: "#F0FDFA",
    borderColor: "#14B8A6",
  },
  editButton: {
    position: "absolute",
    zIndex: 999,
    top: 14,
    right: 14,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#F0FDFA",
    alignItems: "center",
    justifyContent: "center",
  },
  renderFields: {
    marginTop: 12,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  input: {
    backgroundColor: "#FFFFFF",
    color: "#0F172A",
    padding: 10,
    borderRadius: 10,
    marginTop: 4,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  name: {
    fontSize: 22,
    fontWeight: "700",
    color: "#0F172A",
    marginBottom: 2,
  },
  email: {
    fontSize: 14,
    color: "#64748B",
    marginBottom: 10,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  badgeRole: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#F0FDFA",
    color: "#0D9488",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "uppercase",
  },
  badgeStatus: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  badgeActive: {
    backgroundColor: "#ECFDF5",
  },
  badgeBanned: {
    backgroundColor: "#FEF2F2",
  },
  badgeStatusText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#374151",
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    marginRight: 5,
  },
  sectionTitle: {
    marginBottom: 12,
    marginTop: 20,
    padding: 0,
  },
  gradeCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 12,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  gradeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    alignItems: "center",
  },
  gradeTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0F172A",
  },
  gradeSubTitle: {
    fontSize: 12,
    color: "#94A3B8",
  },
  unitsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  unitChip: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
  },
  unitChipActive: {
    backgroundColor: "#F0FDFA",
    borderColor: "#14B8A6",
  },
  unitChipInactive: {
    backgroundColor: "#F8FAFC",
    borderColor: "#E2E8F0",
  },
  unitText: {
    fontSize: 12,
    fontWeight: "500",
  },
  unitTextActive: {
    color: "#0D9488",
  },
  unitTextInactive: {
    color: "#94A3B8",
  },
});
